# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Opration_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.setEnabled(True)
        Form.resize(1120, 530)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1120, 530))
        Form.setMaximumSize(QtCore.QSize(1120, 530))
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/.png/png/1208066.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setWindowOpacity(1.0)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet(_fromUtf8(""))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 20, 1418, 202))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_8.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label.setMinimumSize(QtCore.QSize(180, 30))
        self.label.setMaximumSize(QtCore.QSize(180, 30))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.pushButton_openfile_1 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_openfile_1.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_openfile_1.setMaximumSize(QtCore.QSize(90, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/.png/png/1208069.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_openfile_1.setIcon(icon1)
        self.pushButton_openfile_1.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_openfile_1.setCheckable(False)
        self.pushButton_openfile_1.setChecked(False)
        self.pushButton_openfile_1.setAutoRepeat(False)
        self.pushButton_openfile_1.setAutoExclusive(False)
        self.pushButton_openfile_1.setObjectName(_fromUtf8("pushButton_openfile_1"))
        self.horizontalLayout_2.addWidget(self.pushButton_openfile_1)
        self.lineEdit_filein_1 = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_filein_1.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_filein_1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_filein_1.setObjectName(_fromUtf8("lineEdit_filein_1"))
        self.horizontalLayout_2.addWidget(self.lineEdit_filein_1)
        self.comboBox_tgfiletype = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_tgfiletype.setMinimumSize(QtCore.QSize(60, 27))
        self.comboBox_tgfiletype.setMaximumSize(QtCore.QSize(60, 27))
        self.comboBox_tgfiletype.setObjectName(_fromUtf8("comboBox_tgfiletype"))
        self.comboBox_tgfiletype.addItem(_fromUtf8(""))
        self.comboBox_tgfiletype.addItem(_fromUtf8(""))
        self.comboBox_tgfiletype.addItem(_fromUtf8(""))
        self.comboBox_tgfiletype.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.comboBox_tgfiletype)
        self.pushButton_cf_set1 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_cf_set1.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_cf_set1.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_cf_set1.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/.png/png/settings_284px_1211102_easyicon.net.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_cf_set1.setIcon(icon2)
        self.pushButton_cf_set1.setObjectName(_fromUtf8("pushButton_cf_set1"))
        self.horizontalLayout_2.addWidget(self.pushButton_cf_set1)
        self.pushButton_exefile_1 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_exefile_1.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_exefile_1.setMaximumSize(QtCore.QSize(30, 16777215))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/.png/png/1222647.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_exefile_1.setIcon(icon3)
        self.pushButton_exefile_1.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_exefile_1.setObjectName(_fromUtf8("pushButton_exefile_1"))
        self.horizontalLayout_2.addWidget(self.pushButton_exefile_1)
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setMinimumSize(QtCore.QSize(70, 30))
        self.label_2.setMaximumSize(QtCore.QSize(70, 30))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.textEdit_exestate_1 = QtGui.QTextEdit(self.horizontalLayoutWidget_2)
        self.textEdit_exestate_1.setMaximumSize(QtCore.QSize(80, 30))
        self.textEdit_exestate_1.setUndoRedoEnabled(True)
        self.textEdit_exestate_1.setReadOnly(True)
        self.textEdit_exestate_1.setObjectName(_fromUtf8("textEdit_exestate_1"))
        self.horizontalLayout_2.addWidget(self.textEdit_exestate_1)
        self.pushButton_tg_show = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_tg_show.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_tg_show.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_tg_show.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/.png/png/1194904.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_tg_show.setIcon(icon4)
        self.pushButton_tg_show.setObjectName(_fromUtf8("pushButton_tg_show"))
        self.horizontalLayout_2.addWidget(self.pushButton_tg_show)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setMinimumSize(QtCore.QSize(180, 30))
        self.label_3.setMaximumSize(QtCore.QSize(180, 30))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.pushButton_openfile_2 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_openfile_2.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_openfile_2.setMaximumSize(QtCore.QSize(90, 30))
        self.pushButton_openfile_2.setIcon(icon1)
        self.pushButton_openfile_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_openfile_2.setCheckable(False)
        self.pushButton_openfile_2.setChecked(False)
        self.pushButton_openfile_2.setAutoRepeat(False)
        self.pushButton_openfile_2.setAutoExclusive(False)
        self.pushButton_openfile_2.setObjectName(_fromUtf8("pushButton_openfile_2"))
        self.horizontalLayout_3.addWidget(self.pushButton_openfile_2)
        self.lineEdit_filein_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_filein_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_filein_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_filein_2.setObjectName(_fromUtf8("lineEdit_filein_2"))
        self.horizontalLayout_3.addWidget(self.lineEdit_filein_2)
        self.comboBox_ngfiletype = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_ngfiletype.setMinimumSize(QtCore.QSize(60, 27))
        self.comboBox_ngfiletype.setMaximumSize(QtCore.QSize(60, 27))
        self.comboBox_ngfiletype.setObjectName(_fromUtf8("comboBox_ngfiletype"))
        self.comboBox_ngfiletype.addItem(_fromUtf8(""))
        self.comboBox_ngfiletype.addItem(_fromUtf8(""))
        self.comboBox_ngfiletype.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.comboBox_ngfiletype)
        self.pushButton_cf_set2 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_cf_set2.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_cf_set2.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_cf_set2.setText(_fromUtf8(""))
        self.pushButton_cf_set2.setIcon(icon2)
        self.pushButton_cf_set2.setObjectName(_fromUtf8("pushButton_cf_set2"))
        self.horizontalLayout_3.addWidget(self.pushButton_cf_set2)
        self.pushButton_exefile_2 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_exefile_2.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_exefile_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_exefile_2.setIcon(icon3)
        self.pushButton_exefile_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_exefile_2.setObjectName(_fromUtf8("pushButton_exefile_2"))
        self.horizontalLayout_3.addWidget(self.pushButton_exefile_2)
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setMinimumSize(QtCore.QSize(70, 30))
        self.label_4.setMaximumSize(QtCore.QSize(70, 30))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.textEdit_exestate_2 = QtGui.QTextEdit(self.horizontalLayoutWidget_2)
        self.textEdit_exestate_2.setMaximumSize(QtCore.QSize(80, 30))
        self.textEdit_exestate_2.setUndoRedoEnabled(True)
        self.textEdit_exestate_2.setReadOnly(True)
        self.textEdit_exestate_2.setObjectName(_fromUtf8("textEdit_exestate_2"))
        self.horizontalLayout_3.addWidget(self.textEdit_exestate_2)
        self.pushButton_ng_show = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_ng_show.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_ng_show.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_ng_show.setText(_fromUtf8(""))
        self.pushButton_ng_show.setIcon(icon4)
        self.pushButton_ng_show.setObjectName(_fromUtf8("pushButton_ng_show"))
        self.horizontalLayout_3.addWidget(self.pushButton_ng_show)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_7 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_7.setMinimumSize(QtCore.QSize(180, 30))
        self.label_7.setMaximumSize(QtCore.QSize(180, 30))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.pushButton_openfile_3 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_openfile_3.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_openfile_3.setMaximumSize(QtCore.QSize(90, 30))
        self.pushButton_openfile_3.setIcon(icon1)
        self.pushButton_openfile_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_openfile_3.setCheckable(False)
        self.pushButton_openfile_3.setChecked(False)
        self.pushButton_openfile_3.setAutoRepeat(False)
        self.pushButton_openfile_3.setAutoExclusive(False)
        self.pushButton_openfile_3.setObjectName(_fromUtf8("pushButton_openfile_3"))
        self.horizontalLayout_6.addWidget(self.pushButton_openfile_3)
        self.lineEdit_filein_3 = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_filein_3.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_filein_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_filein_3.setObjectName(_fromUtf8("lineEdit_filein_3"))
        self.horizontalLayout_6.addWidget(self.lineEdit_filein_3)
        self.pushButton_exefile_3 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_exefile_3.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_exefile_3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_exefile_3.setIcon(icon3)
        self.pushButton_exefile_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_exefile_3.setObjectName(_fromUtf8("pushButton_exefile_3"))
        self.horizontalLayout_6.addWidget(self.pushButton_exefile_3)
        self.label_8 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_8.setMinimumSize(QtCore.QSize(70, 30))
        self.label_8.setMaximumSize(QtCore.QSize(70, 30))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_6.addWidget(self.label_8)
        self.textEdit_exestate_3 = QtGui.QTextEdit(self.horizontalLayoutWidget_2)
        self.textEdit_exestate_3.setMaximumSize(QtCore.QSize(80, 30))
        self.textEdit_exestate_3.setUndoRedoEnabled(True)
        self.textEdit_exestate_3.setReadOnly(True)
        self.textEdit_exestate_3.setObjectName(_fromUtf8("textEdit_exestate_3"))
        self.horizontalLayout_6.addWidget(self.textEdit_exestate_3)
        spacerItem1 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_12 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_12.setMinimumSize(QtCore.QSize(180, 30))
        self.label_12.setMaximumSize(QtCore.QSize(180, 30))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_10.addWidget(self.label_12)
        self.comboBox_optimization = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_optimization.setMinimumSize(QtCore.QSize(50, 30))
        self.comboBox_optimization.setMaximumSize(QtCore.QSize(100, 30))
        self.comboBox_optimization.setObjectName(_fromUtf8("comboBox_optimization"))
        self.comboBox_optimization.addItem(_fromUtf8(""))
        self.comboBox_optimization.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.comboBox_optimization)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_9 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_9.setMinimumSize(QtCore.QSize(180, 30))
        self.label_9.setMaximumSize(QtCore.QSize(180, 30))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_7.addWidget(self.label_9)
        self.radioButton_config_op1 = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_config_op1.setMinimumSize(QtCore.QSize(0, 30))
        self.radioButton_config_op1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.radioButton_config_op1.setAutoExclusive(False)
        self.radioButton_config_op1.setObjectName(_fromUtf8("radioButton_config_op1"))
        self.horizontalLayout_7.addWidget(self.radioButton_config_op1)
        self.radioButton_config_op2 = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_config_op2.setMinimumSize(QtCore.QSize(0, 30))
        self.radioButton_config_op2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.radioButton_config_op2.setCheckable(True)
        self.radioButton_config_op2.setAutoExclusive(False)
        self.radioButton_config_op2.setObjectName(_fromUtf8("radioButton_config_op2"))
        self.horizontalLayout_7.addWidget(self.radioButton_config_op2)
        self.radioButton_config_op3 = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_config_op3.setMinimumSize(QtCore.QSize(0, 30))
        self.radioButton_config_op3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.radioButton_config_op3.setAutoExclusive(False)
        self.radioButton_config_op3.setObjectName(_fromUtf8("radioButton_config_op3"))
        self.horizontalLayout_7.addWidget(self.radioButton_config_op3)
        self.radioButton_config_op4 = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_config_op4.setMinimumSize(QtCore.QSize(0, 30))
        self.radioButton_config_op4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.radioButton_config_op4.setAutoExclusive(False)
        self.radioButton_config_op4.setObjectName(_fromUtf8("radioButton_config_op4"))
        self.horizontalLayout_7.addWidget(self.radioButton_config_op4)
        self.comboBox_metric = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_metric.setMinimumSize(QtCore.QSize(60, 27))
        self.comboBox_metric.setMaximumSize(QtCore.QSize(60, 27))
        self.comboBox_metric.setObjectName(_fromUtf8("comboBox_metric"))
        self.comboBox_metric.addItem(_fromUtf8(""))
        self.comboBox_metric.addItem(_fromUtf8(""))
        self.comboBox_metric.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.comboBox_metric)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.pushButton_algorithm_match = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_algorithm_match.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_algorithm_match.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_algorithm_match.setObjectName(_fromUtf8("pushButton_algorithm_match"))
        self.horizontalLayout_7.addWidget(self.pushButton_algorithm_match)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.groupBox = QtGui.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 180))
        self.groupBox.setMaximumSize(QtCore.QSize(300, 180))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.textBrowser_filein_msg = QtGui.QTextBrowser(self.groupBox)
        self.textBrowser_filein_msg.setGeometry(QtCore.QRect(0, 30, 300, 140))
        self.textBrowser_filein_msg.setMinimumSize(QtCore.QSize(300, 140))
        self.textBrowser_filein_msg.setMaximumSize(QtCore.QSize(300, 140))
        self.textBrowser_filein_msg.setObjectName(_fromUtf8("textBrowser_filein_msg"))
        self.horizontalLayout_8.addWidget(self.groupBox)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 240, 1131, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 270, 1041, 221))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setMinimumSize(QtCore.QSize(180, 30))
        self.label_10.setMaximumSize(QtCore.QSize(180, 30))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        self.label_algo_recommend = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_algo_recommend.setObjectName(_fromUtf8("label_algo_recommend"))
        self.horizontalLayout_9.addWidget(self.label_algo_recommend)
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_13.setMinimumSize(QtCore.QSize(70, 30))
        self.label_13.setMaximumSize(QtCore.QSize(70, 30))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_9.addWidget(self.label_13)
        self.radioButton_algorithm_1 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_algorithm_1.setMinimumSize(QtCore.QSize(0, 30))
        self.radioButton_algorithm_1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.radioButton_algorithm_1.setChecked(True)
        self.radioButton_algorithm_1.setObjectName(_fromUtf8("radioButton_algorithm_1"))
        self.horizontalLayout_9.addWidget(self.radioButton_algorithm_1)
        self.radioButton_algorithm_2 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_algorithm_2.setMinimumSize(QtCore.QSize(0, 30))
        self.radioButton_algorithm_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.radioButton_algorithm_2.setObjectName(_fromUtf8("radioButton_algorithm_2"))
        self.horizontalLayout_9.addWidget(self.radioButton_algorithm_2)
        self.radioButton_algorithm_3 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_algorithm_3.setMinimumSize(QtCore.QSize(0, 30))
        self.radioButton_algorithm_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.radioButton_algorithm_3.setObjectName(_fromUtf8("radioButton_algorithm_3"))
        self.horizontalLayout_9.addWidget(self.radioButton_algorithm_3)
        self.pushButton_caculate = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_caculate.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_caculate.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_caculate.setObjectName(_fromUtf8("pushButton_caculate"))
        self.horizontalLayout_9.addWidget(self.pushButton_caculate)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_11.setMinimumSize(QtCore.QSize(100, 30))
        self.label_11.setMaximumSize(QtCore.QSize(100, 30))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_2.addWidget(self.label_11)
        self.textBrowser_algorithm_msg = QtGui.QTextBrowser(self.verticalLayoutWidget_2)
        self.textBrowser_algorithm_msg.setObjectName(_fromUtf8("textBrowser_algorithm_msg"))
        self.verticalLayout_2.addWidget(self.textBrowser_algorithm_msg)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "基于拓扑映射的并行应用通信优化系统", None))
        self.label.setText(_translate("Form", "应用进程拓扑数据文件输入", None))
        self.pushButton_openfile_1.setText(_translate("Form", "打开", None))
        self.comboBox_tgfiletype.setItemText(0, _translate("Form", ".APHiD", None))
        self.comboBox_tgfiletype.setItemText(1, _translate("Form", ".mat", None))
        self.comboBox_tgfiletype.setItemText(2, _translate("Form", ".txt", None))
        self.comboBox_tgfiletype.setItemText(3, _translate("Form", "Dir", None))
        self.pushButton_cf_set1.setToolTip(_translate("Form", "设置", None))
        self.pushButton_exefile_1.setText(_translate("Form", "文件解析", None))
        self.label_2.setText(_translate("Form", "解析状态：", None))
        self.pushButton_tg_show.setToolTip(_translate("Form", "查看", None))
        self.label_3.setText(_translate("Form", "计算节点拓扑数据文件输入", None))
        self.pushButton_openfile_2.setText(_translate("Form", "打开", None))
        self.comboBox_ngfiletype.setItemText(0, _translate("Form", ".txt", None))
        self.comboBox_ngfiletype.setItemText(1, _translate("Form", ".tgt", None))
        self.comboBox_ngfiletype.setItemText(2, _translate("Form", ".xml", None))
        self.pushButton_cf_set2.setToolTip(_translate("Form", "设置", None))
        self.pushButton_exefile_2.setText(_translate("Form", "文件解析", None))
        self.label_4.setText(_translate("Form", "解析状态：", None))
        self.pushButton_ng_show.setToolTip(_translate("Form", "查看", None))
        self.label_7.setText(_translate("Form", "配置数据文件输入", None))
        self.pushButton_openfile_3.setText(_translate("Form", "打开", None))
        self.pushButton_exefile_3.setText(_translate("Form", "文件解析", None))
        self.label_8.setText(_translate("Form", "解析状态：", None))
        self.label_12.setText(_translate("Form", "优化选项", None))
        self.comboBox_optimization.setItemText(0, _translate("Form", "performance", None))
        self.comboBox_optimization.setItemText(1, _translate("Form", "efficiency", None))
        self.label_9.setText(_translate("Form", "配置选项", None))
        self.radioButton_config_op1.setText(_translate("Form", "配置选项1", None))
        self.radioButton_config_op2.setText(_translate("Form", "配置选项1", None))
        self.radioButton_config_op3.setText(_translate("Form", "配置选项1", None))
        self.radioButton_config_op4.setText(_translate("Form", "配置选项1", None))
        self.comboBox_metric.setItemText(0, _translate("Form", "SUM_COM", None))
        self.comboBox_metric.setItemText(1, _translate("Form", "MAX_COM", None))
        self.comboBox_metric.setItemText(2, _translate("Form", "HOP_BYTE", None))
        self.pushButton_algorithm_match.setText(_translate("Form", "可用算法匹配", None))
        self.groupBox.setTitle(_translate("Form", "文件输入操作提示：", None))
        self.textBrowser_filein_msg.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">文件输入操作提示：</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.label_10.setText(_translate("Form", "算法推荐", None))
        self.label_algo_recommend.setText(_translate("Form", "TopoMapping", None))
        self.label_13.setText(_translate("Form", "算法选择", None))
        self.radioButton_algorithm_1.setText(_translate("Form", "算法1", None))
        self.radioButton_algorithm_2.setText(_translate("Form", "算法2", None))
        self.radioButton_algorithm_3.setText(_translate("Form", "算法3", None))
        self.pushButton_caculate.setText(_translate("Form", "开始计算", None))
        self.label_11.setText(_translate("Form", "算法概要：", None))

import sourcefile_rc
